### PR TITLE
rules: do not require natspect title on functions

### LINKED ISSUE #24: missing-natspec-comments incorrectly emits missing title on functions
In `missing-natspec-comments` [functions are added to the list of nodes to be evaluated](https://github.com/OpenZeppelin/solium-plugin-zeppelin/blob/master/rules/missing-natspec-comments.js#L39) and it checks that [they have a title](https://github.com/OpenZeppelin/solium-plugin-zeppelin/blob/master/rules/missing-natspec-comments.js#L61).

However, according to the [format specification](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format#tags) `@title` applies only to `contract` and `interface`, not `function`.

In fact, adding a `@title` to a function natspec will result in `solc` reporting: 

```
DocstringParsingError: Doc tag @title not valid for functions.
```

### PR DESCRIPTION
**Pull request by elopio**
Closes #24

### CODE REVIEW

File: test/missing-natspec-comments.js [hunk 1]
```diff
@@ -213,4 +199,32 @@ describe("[RULE] missing-natspec-comments: Acceptances", function() {
         done();
     });
 
+    // Regression test for
+    // https://github.com/OpenZeppelin/solium-plugin-zeppelin/issues/24
+    it("should accept functions without natspec title", function(done) {
+        let scenarios = [
+            "/// @title dummy comment.\n" +
```
Comment (frangio) [inline test/missing-natspec-comments.js]: We should look into using template strings for this.

File: test/missing-natspec-comments.js [hunk 2]
```diff
@@ -213,4 +199,32 @@ describe("[RULE] missing-natspec-comments: Acceptances", function() {
...
+            "    /**\n" +
+            "     Natspec comment without title.\n" +
+            "     */\n" +
+            "    function TestStatement() {}\n" +
+            "}"
+        ];
+        scenarios.forEach(code => {
+            let errors = Solium.lint(addPragma(code), userConfig);
+
+            errors.constructor.name.should.equal("Array");
```
Comment (frangio) [inline test/missing-natspec-comments.js]: Unless I'm missing something, the more idiomatic thing you want here is an `instanceof` type of comparison. In Chai we can apparently do `errors.should.be.instanceof(Array)`.

Comment (elopio) [reply test/missing-natspec-comments.js]: @frangio very nice suggestions. This is all new to me, and I just copied all the style from solium. I will prepare two branches to change all the template literals and all the instanceof comparisons.
Thanks for the review! Landing...
